Music playlist down script: guard for mismatch between 'Album.txt' and 'AlbumTitles.txt' to prevent invalid file names

diff --git a/music_playlist_down b/music_playlist_down
--- a/music_playlist_down
+++ b/music_playlist_down
@@ -179,7 +179,7 @@ function step_2() {
   echo "Step 2: Downloading audio from playlist..."
 
   if [ ! -f "$YOUTUBE_IDS_FILE" ]; then
-    echo "Cannot find YouTube playlist IDs file: $YOUTUBE_IDS_FILE"
+    echo "Error: Cannot find YouTube playlist IDs file: $YOUTUBE_IDS_FILE"
     exit 1
   fi
 
@@ -214,6 +214,13 @@ function step_3() {
   while IFS= read -r title; do
     SANITIZED_TITLES+=("$(sanitize_filename "$title")")
   done <<< "$(cat "$YOUTUBE_IDS_META_FILE")"
+
+  if [ "$(wc "$YOUTUBE_IDS_FILE" -l | awk '{print $1}')" != "${#SANITIZED_TITLES[@]}" ]; then
+    echo "Error: Line count mismatch between '$YOUTUBE_IDS_META_FILE' and '$YOUTUBE_IDS_FILE'"
+    echo "Both files must have the same number of lines. Line <N> in '$YOUTUBE_IDS_META_FILE' must correspond to line <N> in '$YOUTUBE_IDS_FILE'"
+    echo "Tip: to resume from this step, use --step 3"
+    exit 1
+  fi
 
   echo "Renaming files..."
   local ind=0
